# Permalinks
permalink:        pretty

# Setup
title:            "Python Beginner's Handbook"
tagline:          ''
description:      "Concepts, instructions, and a quick-reference for the beginning Python programmer."
url:              https://lilhandsbgdreams.github.io/python-handbook/
baseurl:          /python-handbook

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/lilhandsbgdreams/python-handbook

# Dependencies
markdown:         kramdown
highlighter:      rouge